### ISSUE TITLE
"create_quote" throws exception

### ISSUE THREAD

**Issue by WillemWikkelspies** [luno/luno-python#27]
Starting on 24/03/2021, when creating a quote, the following exception is returned

```
Traceback (most recent call last):
  File "/home/pi/Desktop/LTB/LunoApi.py", line 130, in Quote
    res = c.create_quote(base_amount = b, pair = p, type = t)
  File "/usr/local/lib/python3.7/dist-packages/luno_python/client.py", line 115, in create_quote
    return self.do('POST', '/api/1/quotes', req=req, auth=True)
  File "/usr/local/lib/python3.7/dist-packages/luno_python/base_client.py", line 84, in do
    e = res.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
```
Example 
`create_quote(base_amount = "100" , pair = "XRPZAR", type = "SELL")`

**Comment by echarrod** [comment]
Hi @WillemWikkelspies, apologies no one got back to you about this, is it still an issue?

**Comment by echarrod** [comment]
Closing due to inactivity
