### ISSUE TITLE
Never mind

### ISSUE THREAD

**Issue by DrZondagh** [luno/luno-python#49]

**Comment by DrZondagh** [comment]
Error msg:
Traceback (most recent call last):
  File "C:\Users\user1\PycharmProjects\project_1\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexion.loads(self.text, **kwargs)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user1\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\PycharmProjects\project_1\venv\lib\site-packages\luno_python\base_client.py", line 84, in do
    e = res.json()
  File "C:\Users\user1\PycharmProjects\project_1\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\PycharmProjects\project_1\exchange.py", line 48, in <module>
    e = funds_available()
  File "C:\Users\user1\PycharmProjects\project_1\exchange.py", line 45, in funds_available
    res = c.get_balances(assets=['XBT', 'ZAR'])
  File "C:\Users\user1\PycharmProjects\project_1\venv\lib\site-packages\luno_python\client.py", line 132, in get_balances
    return self.do('GET', '/api/1/balance', req=req, auth=True)
  File "C:\Users\user1\PycharmProjects\project_1\venv\lib\site-packages\luno_python\base_client.py", line 89, in do
    raise Exception('luno: unknown API error (%s)' % res.status_code)
Exception: luno: unknown API error (401)
